config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"

  resources :offers

  namespace 'api' do
    namespace 'v1' do
      resources :offers
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord
  include AASM

  attr_accessor :current_user_admin

  enum state: {disabled: 0, enabled: 1}

  validates :advertiser_name, :url, :description, :starts_at, presence: true
  validates :advertiser_name, uniqueness:true, length: {minimum: 3}
  validates :description, length: {maximum: 500 }
  validates :url, format: URI::regexp(%w[http https])

  aasm column: :state, enum: true do
    state :disabled, initial: true
    state :enabled

    event :enable do
      transitions from: :disabled, to: :enabled, guard: :can_enable?
    end

    event :disable do
      transitions from: :enabled, to: :disabled, guard: :can_disable?
    end
  end

  scope :may_enable, -> do
    offers = []
    disabled.find_each do |offer|
      offers << offer if offer.may_enable?
    end

    offers
  end

  scope :may_disable, -> do
    offers = []
    enabled.find_each do |offer|
      offers << offer if offer.may_disable?
    end

    offers
  end

  scope :order_enabled_premium, -> do
    enabled.order(premium: :desc, id: :asc)
  end

  scope :order_state, -> do
    order(state: :desc, id: :asc)
  end

  private

  def can_enable?
    state_policy.can_enable?
  end

  def can_disable?
    state_policy.can_disable?
  end

  def state_policy
    OfferStatePolicy.new(starts_at, ends_at, current_user_admin)
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum role: { user: 0, admin: 1 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/base_controller.rb
module Api
  class BaseController < ActionController::API
    before_action :http_basic_authenticate

    def http_basic_authenticate
      token = request.authorization.split(' ')
      decode = Base64.decode64(token[1]).split(':')

      user = decode[0]
      password = decode[1]

      unless user == 'lyoncesar' && password == 'password'
        render json: '', status: 403
      end
    end
  end
end

app/controllers/api/v1/offers_controller.rb
module Api
  module V1
    class OffersController < Api::BaseController
      def index
        @offers = Offer.order('created_at DESC')
        render json: OfferSerializer.new(Offer.all).serialized_json, status: :ok
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :authenticate_user!
  layout :layout_by_resource

  def layout_by_resource
    return "devise" if devise_controller?

    "application"
  end

  def admin_user?
    current_user.admin?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @offers = Offer.order_enabled_premium
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :current_offer, only: %w[edit destroy]
  before_action :authorize_admin

  def index
    @offers = Offer.order_state
  end

  def new
    @offer = Offer.new
  end

  def edit
  end

  def create
    @offer = Offer.new(offer_params)

    if @offer.save
      redirect_to offers_path, notice: "The offer #{@offer.advertiser_name} been created."
    else
      flash.now['error'] = @offer.errors.full_messages
      render :new
    end
  end

  def update
    update = OfferUpdate.new(params[:id], offer_params, admin_user?)

    if update.call
      redirect_to offers_path,
        notice: "The offer #{update.current_offer.advertiser_name} been updated."
    else
      @offer = update.current_offer
      flash.now['error'] = @offer.errors.full_messages
      render :edit
    end
  end

  def destroy
    @offer.destroy
    redirect_to offers_path, notice: "The offer been deleted."
  end

  private

  def authorize_admin
    return if current_user.admin?

    redirect_to root_path, notice: 'This page only accessible by admin users.'
  end

  def current_offer
    @offer = Offer.find(params.dig(:id))
  end

  def offer_params
    params.require(:offer).permit(
      :advertiser_name,
      :url,
      :description,
      :state,
      :starts_at,
      :ends_at,
      :premium
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def minimum_password_length(min_pass_length)
    if min_pass_length
      t('users.password_min_length', min_length: min_pass_length)
    else
      t('users.password')
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def admin_offers
    if current_user.admin?
      content_tag(:div) do
        link_to t('home.offers_admin'), offers_path, :class => 'btn btn-link float-right'
      end
    end
  end

  def offer_premium(offer_premium)
    if offer_premium
      content_tag(:div, class: 'text-right') do
        content_tag(:span, t('home.premium'), class: 'badge badge-danger badge-premium border border-light rounded-pill position-absolute  shadow')
      end
    end
  end
end

app/helpers/navigation_helper.rb
module NavigationHelper
  def user_signed_in_email
    if user_signed_in?
      content_tag(:span, "#{current_user.email}", :class => 'navbar-text text-light nav-righ')
    end
  end

  def user_signed_in_edit
    if user_signed_in?
      content_tag(:li, class: "nav-item") do
        link_to t('users.edit'), edit_user_registration_path, :class => 'nav-link text-light nav-righ'
      end
    else
      content_tag(:li, class: "nav-item") do
        link_to t('users.sign_up'), new_user_registration_path, :class => 'nav-link text-light nav-righ'
      end
    end
  end

  def user_signed_in_logout
    if user_signed_in?
      content_tag(:li, class: "nav-item") do
        link_to t('sessions.logout'), destroy_user_session_path, method: :delete, :class => 'nav-link text-light nav-righ'
      end
    else
      content_tag(:li, class: "nav-item") do
        link_to t('sessions.login'), new_user_session_path, :class => 'nav-link text-light nav-righ'
      end
    end
  end

  def user_signed_in_home
    if user_signed_in?
      content_tag(:div) do
        link_to(
          image_tag('logo.png',
                    :class => 'row align-self-center mb-2',
                    :width => '62',
                    :height => '62'
                   ),
          root_path, :class => 'navbar-brand text-light')
      end
    end
  end
end

app/helpers/offers_helper.rb
module OffersHelper
  def offer_new_state(state)
    return t('offers.disabled') if state == 'enabled'

    t('offers.enabled')
  end

  def offer_new_state_option(state)
    return t('offers.disable') if state == 'enabled'

    t('offers.enable')
  end
end

app/views/home/index.html.erb
<div>
  <div class="mt-3 mb-4">
    <%= admin_offers %>
    <h1><%= t('home.todays_offers')  %></h1>
  </div>

  <div class="row row-cols-1 row-cols-md-2">
    <% @offers.each do |offer| %>
      <div class="col mb-4">
        <div class="card rounded w-100 p-3">
           <%= offer_premium(offer.premium) %>
          <div class="card-body text-center">
            <h4 class="card-title my-2"><%= offer.advertiser_name %></h4>
            <p class "card-text"></p>
            <%= link_to t('home.shop_now'), offer.url, class: 'btn-hover-green btn btn-sm btn-primary w-50 p-3', target: '_blank' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cashback</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_pack_tag 'application', media: 'all','data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <%= render 'shared/navigation' %>
    </header>

    <main role="main">
      <div class="container container-height">
        <%= render 'shared/messages' %>
        <%= yield %>
      </div>
    </main>

    <footer class="page-footer">
      <%= render 'shared/footer' %>
    </footer>

  </body>

</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cashback</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light-green">
    <div class="row mx-auto text-center align-items-center" style="width: 300px; height: 100vh">
      <div class="form-signin col-md-12">
        <%= render 'shared/messages' %>
        <%= yield %>
      </div>
    </div>
  </body>

</html>

app/views/offers/_form.html.erb
<div>
  <%= form_for @offer do |f| %>
    <div class="form-group">
        <%= f.label :advertiser_name, 'Advertiser name'  %>
        <%= f.text_field :advertiser_name, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :url, 'URL' %>
        <%= f.text_field :url, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :description, 'Description' %>
        <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :starts_at, 'Starts at' %>
        <%= f.date_field :starts_at, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :ends_at, 'Ends at' %>
        <%= f.date_field :ends_at, class: 'form-control' %>
    </div>
    <div class="form-group form-check">
        <%= f.check_box :premium, class: 'form-check-input' %>
        <%= f.label :premium, 'Premium', class: 'form-check-label' %>
    </div>
    <div class="alig">
      <%= f.submit t('offers.submit'), class: 'btn btn-primary btn-lg btn-block' %>
    </div>
  <% end %>
</div>

app/views/offers/edit.html.erb
<h1>Edit offer <%= @offer.advertiser_name %></h1>

<div>
  <%= link_to 'Back to offers', offers_path %>
</div>

<%= render 'form', locals: {offer: @offer} %>

app/views/offers/index.html.erb
<div>
  <div class="mt-3 mb-4">
    <h1><%= t('offers.title') %></h1>
  </div>

  <div class="table-responsive">
    <table class="table table-bordered">
      <div>
        <%= link_to t('offers.new'), new_offer_path, class: 'btn btn-link float-right' %>
      </div>
      <thead class="thead-dark">
        <tr>
          <th scope="col"><%= t('offers.id') %></th>
          <th scope="col"><%= t('offers.name') %></th>
          <th scope="col"><%= t('offers.url')  %></th>
          <th scope="col"><%= t('offers.state') %></th>
          <th scope="col"><%= t('offers.actions') %></th>
        </tr>
      </thead>
      <tbody>
        <% @offers.each do |offer| %>
          <tr>
            <th scope="row"><%= offer.id %></th>
            <td><%= offer.advertiser_name %></td>
            <td><%= offer.url %></td>
            <td><%= offer.state.titleize %></td>
            <td>
              <%= link_to t('offers.edit'), edit_offer_path(offer) %> |
              <%= link_to offer_new_state_option(offer.state), [offer, { offer: {state: offer_new_state(offer.state)} }], method: :patch %> |
              <%= link_to t('offers.destroy'), offer_path(offer), method: :delete, data: {confirm: t('offers.destroy_message')} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/offers/new.html.erb
<div class="mt-3 mb-4">
  <%= link_to t('offers.admin_offers'), offers_path, :class => 'btn btn-link float-right' %>
  <h1><%= t('offers.new_offer') %></h1>
</div>

<div class="rounded p-5 bg-light">
  <%= render 'form', locals: {offer: @offer} %>
</div>

app/views/shared/_footer.html.erb
<div class="font-small indigo pt-4 mt-4">
  <nav class="navbar navbar-dark bg-dark">
    <div class="row mx-auto flex-row">
      <%= image_tag('logo.png', :class => 'mb-4', :width => '62', :height => '62') %>
      <div class="py-3 text-light">
        <%= t('footer.think') %>
      </div>
    </div>
  </nav>
</div>

app/views/shared/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <%= value %>
  </div>
<% end %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-success">
  <div class="container">
    <%= user_signed_in_home %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="ml-auto">
      <div class="collapse navbar-collapse" id="navbarText">
        <%= user_signed_in_email %>
        <ul class='navbar-nav mr-auto nav-righ'>
          <%= user_signed_in_edit %>
          <%= user_signed_in_logout %>
        </ul>
      </div>
    </div>
  </div>
</nav>